#!/usr/bin/env bun
/**
 * Downloads litter-item icons from Serebii into public/litter/<slug>.png and
 * writes src/data/litter-items.generated.ts mapping each item display name to
 * its local sprite path.
 *
 * Source: https://www.serebii.net/pokemonpokopia/litter.shtml. Run once and
 * commit both the PNGs and the generated TS module.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dir, '..');
const OUT_DIR = resolve(ROOT, 'public/litter');
const OUT_DATA = resolve(ROOT, 'src/data/litter-items.generated.ts');
const PAGE_URL = 'https://www.serebii.net/pokemonpokopia/litter.shtml';

mkdirSync(OUT_DIR, { recursive: true });

const html = await (await fetch(PAGE_URL)).text();
const re = /items\/([a-zA-Z0-9_-]+\.png)" height="50" alt="([^"]+)"/g;
const items = new Map<string, { file: string; url: string }>();
for (const m of html.matchAll(re)) {
  const file = m[1];
  const name = m[2];
  if (!file || !name) continue;
  if (!items.has(name)) {
    items.set(name, { file, url: `https://www.serebii.net/pokemonpokopia/items/${file}` });
  }
}

console.log(`found ${items.size} unique litter items`);

let downloaded = 0;
let skipped = 0;
let failed = 0;

for (const [name, info] of items) {
  const dest = resolve(OUT_DIR, info.file);
  if (existsSync(dest)) {
    skipped++;
    continue;
  }
  try {
    const res = await fetch(info.url);
    if (!res.ok) {
      console.warn(`! ${name} (${info.url}): HTTP ${res.status}`);
      failed++;
      continue;
    }
    const buf = new Uint8Array(await res.arrayBuffer());
    writeFileSync(dest, buf);
    downloaded++;
  } catch (err) {
    console.warn(`! ${name}: ${(err as Error).message}`);
    failed++;
  }
}

console.log(`download: ${downloaded} new, ${skipped} cached, ${failed} failed`);

if (failed > 0) process.exit(1);

const banner =
  '// GENERATED by scripts/mirror-litter.ts. Re-run: bun run scripts/mirror-litter.ts\n// DO NOT EDIT BY HAND.\n';
const sortedEntries = Array.from(items.entries()).sort(([a], [b]) => a.localeCompare(b));
const json = JSON.stringify(
  Object.fromEntries(sortedEntries.map(([name, info]) => [name, `/litter/${info.file}`])),
  null,
  2,
);
writeFileSync(
  OUT_DATA,
  `${banner}\nexport const LITTER_ITEM_SPRITES: Readonly<Record<string, string>> = ${json} as const;\n`,
);
console.log(`wrote ${items.size} mappings to ${OUT_DATA}`);
