#!/usr/bin/env bun
/**
 * Downloads specialty icons from pokopia.guide into public/specialties/<slug>.png
 * and writes src/data/specialty-icons.generated.ts mapping each Specialty name
 * to its local sprite path.
 *
 * Source: https://pokopia.guide/data/specialties/<slug>.png. Run once and
 * commit both the PNGs and the generated TS module.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { SPECIALTIES } from '../src/data/specialties';

const ROOT = resolve(import.meta.dir, '..');
const OUT_DIR = resolve(ROOT, 'public/specialties');
const OUT_DATA = resolve(ROOT, 'src/data/specialty-icons.generated.ts');
mkdirSync(OUT_DIR, { recursive: true });

function slug(name: string): string {
  return name.toLowerCase().replace(/\s+/g, '-');
}

let downloaded = 0;
let skipped = 0;
let failed = 0;
const map: Record<string, string> = {};

for (const name of SPECIALTIES) {
  if (name === '???') continue; // no icon for the placeholder specialty
  const s = slug(name);
  const dest = resolve(OUT_DIR, `${s}.png`);
  if (!existsSync(dest)) {
    const url = `https://pokopia.guide/data/specialties/${s}.png`;
    try {
      const res = await fetch(url);
      if (!res.ok) {
        console.warn(`! ${name} (${url}): HTTP ${res.status}`);
        failed++;
        continue;
      }
      const buf = new Uint8Array(await res.arrayBuffer());
      writeFileSync(dest, buf);
      downloaded++;
    } catch (err) {
      console.warn(`! ${name}: ${(err as Error).message}`);
      failed++;
      continue;
    }
  } else {
    skipped++;
  }
  map[name] = `/specialties/${s}.png`;
}

console.log(`download: ${downloaded} new, ${skipped} cached, ${failed} failed`);
if (failed > 0) process.exit(1);

const banner =
  '// GENERATED by scripts/mirror-specialties.ts. Re-run: bun run scripts/mirror-specialties.ts\n// DO NOT EDIT BY HAND.\n';
writeFileSync(
  OUT_DATA,
  `${banner}\nexport const SPECIALTY_ICONS: Readonly<Record<string, string>> = ${JSON.stringify(map, null, 2)} as const;\n`,
);
console.log(`wrote ${Object.keys(map).length} mappings to ${OUT_DATA}`);
