// GENERATED by scripts/mirror-litter.ts. Re-run: bun run scripts/mirror-litter.ts
// DO NOT EDIT BY HAND.

export const LITTER_ITEM_SPRITES: Readonly<Record<string, string>> = {
  Fluff: '/litter/fluff.png',
  Honey: '/litter/honey.png',
  'Iron Ore': '/litter/ironore.png',
  Leaf: '/litter/leaf.png',
  'Nonburnable Garbage': '/litter/nonburnablegarbage.png',
  'Small log': '/litter/smalllog.png',
  'Squishy Clay': '/litter/squishyclay.png',
  Stone: '/litter/stone.png',
  'Sturdy Stick': '/litter/sturdystick.png',
  Twine: '/litter/twine.png',
  'Vine Rope': '/litter/vinerope.png',
} as const;
